### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/march-developers#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, you'll be added as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by gsirsat** [comment]
add me please.

**Comment by gmacario** [comment]
Me too, thanks!

**Comment by leefp** [comment]
yes, please...

**Comment by ravalharshb** [comment]
add me please

**Comment by kilpae** [comment]
Please add me

**Comment by EricVook** [comment]
Add me please. :smile_cat:

**Comment by cwright310** [comment]
add

**Comment by deanemc** [comment]
add me

**Comment by ChandlerLutz** [comment]
Can you please add me as a collaborator??

**Comment by nick15771** [comment]
add me please

**Comment by pavankumarvutukuri** [comment]
Add me please

**Comment by Turnev** [comment]
Please add me

**Comment by kmpetersondell** [comment]
Add me please.

**Comment by ChBoler** [comment]
Requesting to be added

**Comment by ethierKevin** [comment]
Please add me as well

**Comment by sefroberg** [comment]
please add me

**Comment by jbluestein** [comment]
add me, please...

**Comment by sharihovey** [comment]
Comment

**Comment by meghanakatta** [comment]
add me , please

**Comment by majmera** [comment]
Please add me!

**Comment by tnewcomb** [comment]
add me please

**Comment by zzzjie** [comment]
add me please, thanks

**Comment by ronaklotia** [comment]
Add me

**Comment by ssbist** [comment]
Add me. Thanks.

**Comment by kristinawalker** [comment]
add

**Comment by dadkisson** [comment]
please add me

**Comment by MeuLindo** [comment]
Anything you want

**Comment by chrismartino** [comment]
Comment!

**Comment by Probeless** [comment]
I'm in!

**Comment by zcwillia** [comment]
me too

**Comment by irina81** [comment]
add me, please!

**Comment by venkam4** [comment]
Joined the training.

**Comment by udos** [comment]
thx

**Comment by sutcliffesEMC** [comment]
Add me please.

**Comment by misstonbon** [comment]
Add me please.

**Comment by cohenl5** [comment]
Please add me

**Comment by tdavidsmith** [comment]
Add me please.

**Comment by thaidar** [comment]
+me

**Comment by emccyc** [comment]
Hello world!

**Comment by jayeshsaita** [comment]
Hey, add me :)

**Comment by kellypage** [comment]
Hello, please add me.

**Comment by cankartal** [comment]
can you please add me ?

**Comment by votnet** [comment]
and me please

**Comment by goudreau** [comment]
Kenneth, what is the frequency?

**Comment by ramanaj** [comment]
Please add me.

**Comment by stevemallett** [comment]
Ooo - pick me, pick me!

**Comment by zhangt6** [comment]
add me please.

**Comment by balaca86** [comment]
add me!

**Comment by colonial07** [comment]
add me please

**Comment by brown922** [comment]
please add me

**Comment by arussell307** [comment]
+me

**Comment by chens20** [comment]
add me, please

**Comment by coxa5** [comment]
Requesting permission to be added.

**Comment by Danielle-Miller** [comment]
Please add me.

**Comment by kniese** [comment]
Add me please

**Comment by dilgeg** [comment]
Please add

**Comment by mmanning97** [comment]
Add Me

**Comment by jeff-johnson-emc** [comment]
Okey doke

**Comment by mcgrab53** [comment]
Add me too.

**Comment by warrenburnside** [comment]
please add me

**Comment by ntran** [comment]
please add me

**Comment by arpann2** [comment]
Add me please. 👍

**Comment by githubteacher** [comment]
:tada: @gsirsat, @gmacario, @leefp, @ravalharshb, @kilpae, @EricVook, @cwright310, @deanemc, @ChandlerLutz, @nick15771, @pavankumarvutukuri, @Turnev, @kmpetersondell, @ChBoler, @ethierKevin, @sefroberg, @jbluestein, @sharihovey, @meghanakatta, @majmera, @tnewcomb, @zzzjie, @ronaklotia, @ssbist, @kristinawalker, @dadkisson, @ashj1, @MeuLindo, @chrismartino, @Probeless, @zcwillia, @irina81, @venkam4, @udos, @sutcliffesEMC, @misstonbon, @cohenl5, @tdavidsmith, @thaidar, @emccyc, @jayeshsaita, @kellypage, @cankartal, @votnet, @goudreau, @ramanaj, @stevemallett, @zhangt6, @balaca86, @colonial07, @brown922, @arussell307, @chens20, @coxa5, @Danielle-Miller, @kniese, @dilgeg, and @mmanning97 are now  repository collaborators. :balloon:

**Comment by mohitgarg** [comment]
Collabrator

**Comment by randyport** [comment]
add me

**Comment by differentreality** [comment]
Thank you for the webinar!

**Comment by venedara** [comment]
Please Add Me

**Comment by petebreton** [comment]
add me

**Comment by milasr** [comment]
Add me please.

**Comment by risticborivoje** [comment]
Hello

**Comment by ccresap** [comment]
please add me

**Comment by sarahland** [comment]
Hi, add me please.

**Comment by huangkenny** [comment]
Hi. Please add me.

**Comment by Modupeh** [comment]
Modupeh

**Comment by wayne927** [comment]
hi add me plzz!!!

**Comment by dellemc2** [comment]
Hi

**Comment by sathat** [comment]
Add me too

**Comment by mburriss** [comment]
Hi.  Please add me.

**Comment by rafoulks** [comment]
comment here

**Comment by fonsej2** [comment]
Add me please

**Comment by joriswils1** [comment]
add me please

**Comment by svietry** [comment]
Hi, Please add me

**Comment by anicely1** [comment]
add me please

**Comment by badakim1091** [comment]
Hello!

**Comment by richygerard** [comment]
add me

**Comment by msato1013** [comment]
Please add me in

**Comment by githubteacher** [comment]
:tada: @jeff-johnson-emc, @mcgrab53, @warrenburnside, @ntran, @arpann2, @mohitgarg, @randyport, @differentreality, @venedara, @petebreton, @milasr, @risticborivoje, @ccresap, @sarahland, @huangkenny, @Modupeh, @wayne927, @dellemc2, @sathat, @mburriss, @rafoulks, @fonsej2, @joriswils1, @svietry, @anicely1, @badakim1091, @richygerard, and @msato1013 are now  repository collaborators. :balloon:

**Comment by singharvinder** [comment]
add me please

**Comment by aboovv** [comment]
comment

**Comment by dookie3333** [comment]
please add me as a collaborator

**Comment by RobinTera** [comment]
Add me

**Comment by dellmsijka** [comment]
me too

**Comment by AaronZhang-EMC** [comment]
add me please. thanks!

**Comment by khirnak** [comment]
add pls

**Comment by XiaotingXu** [comment]
Add me.
Thank you.

**Comment by narutokiran** [comment]
Add me

**Comment by cjamescook** [comment]
Add me?

**Comment by btanski** [comment]
add me

**Comment by sunzoje** [comment]
add me please

**Comment by vharsh** [comment]
Add me please :smile: :smiley:

**Comment by githubteacher** [comment]
:tada: @singharvinder, @aboovv, @dookie3333, @RobinTera, @dellmsijka, @AaronZhang-EMC, @khirnak, @XiaotingXu, @narutokiran, @cjamescook, @btanski, @sunzoje, and @vharsh are now  repository collaborators. :balloon:

**Comment by sujinecho** [comment]
Add me please

**Comment by DavePDaveP** [comment]
hi

**Comment by jschuler** [comment]
Add me too!

**Comment by casemm01** [comment]
add me please

**Comment by githubteacher** [comment]
:tada: @sujinecho, @DavePDaveP, @jschuler, and @casemm01 are now  repository collaborators. :balloon:

**Comment by donaldcarson** [comment]
hello

**Comment by lohith444** [comment]
+me

**Comment by josea2** [comment]
+me

**Comment by revurp** [comment]
please add me as well

**Comment by brionphilbin** [comment]
+me

**Comment by shilpanikte** [comment]
add me

**Comment by githubteacher** [comment]
:tada: @donaldcarson, @lohith444, @josea2, @revurp, @brionphilbin, and @shilpanikte are now  repository collaborators. :balloon:

**Comment by aanselmi3954** [comment]
add me please

**Comment by mahas4u** [comment]
add me

**Comment by DevendranGitHub** [comment]
please add me

**Comment by stevemallett** [comment]
please & thanks.

**Comment by zhaojingyan1** [comment]
please add me. Thank you!

**Comment by Unilord** [comment]
add  me too thanks

**Comment by githubteacher** [comment]
:tada: @aanselmi3954, @mahas4u, @DevendranGitHub, @zhaojingyan1, and @Unilord are now  repository collaborators. :balloon:

**Comment by dlusby** [comment]
Please add me.  Thanks!

**Comment by goodwb1** [comment]
add me too

**Comment by githubteacher** [comment]
:tada: @dlusby and @goodwb1 are now  repository collaborators. :balloon:

**Comment by pateld2** [comment]
Add me too.

**Comment by phehep** [comment]
Add me please

**Comment by ngtim1** [comment]
Add me too.

**Comment by shennychacko** [comment]
add me too

**Comment by githubteacher** [comment]
:tada: @pateld2, @phehep, @ngtim1, and @shennychacko are now  repository collaborators. :balloon:

**Comment by qingchu7** [comment]
please add me too. thanks

**Comment by mayfid** [comment]
Please add me

**Comment by dreamchazer** [comment]
Please add me

**Comment by githubteacher** [comment]
:tada: @qingchu7, @mayfid, and @dreamchazer are now  repository collaborators. :balloon:

**Comment by buchhei** [comment]
Please Add me

**Comment by dossa1** [comment]
add me please

**Comment by sunw3** [comment]
add me please

**Comment by mhamel12** [comment]
Please add me as a collaborator

**Comment by gserviss** [comment]
please add me

**Comment by githubteacher** [comment]
:tada: @buchhei, @dossa1, @sunw3, @mhamel12, and @gserviss are now  repository collaborators. :balloon:

**Comment by michelp70** [comment]
Hi, please add me.

**Comment by Aerostation** [comment]
Please add as a collaborator

**Comment by byu2233** [comment]
please add me

**Comment by SuiHoang** [comment]
Please add me. Thanks!

**Comment by srinidhirvce** [comment]
add me

**Comment by kotteson** [comment]
please add me...thanks

**Comment by githubteacher** [comment]
:tada: @michelp70, @Aerostation, @byu2233, @SuiHoang, @srinidhirvce, and @kotteson are now  repository collaborators. :balloon:

**Comment by svietry** [comment]
Hi K.  @khirnak

**Comment by hug-yq** [comment]
add me please

**Comment by mingju** [comment]
add me please.

**Comment by rachelliao2016** [comment]
add me please

**Comment by desaiz** [comment]
add me

**Comment by PhaneendraReddy** [comment]
Add me please

**Comment by refrazie** [comment]
add me plz

**Comment by lucasruchel** [comment]
add me please

**Comment by githubteacher** [comment]
:tada: @hug-yq, @mingju, @rachelliao2016, @desaiz, @PhaneendraReddy, @refrazie, and @lucasruchel are now  repository collaborators. :balloon:

**Comment by carol299** [comment]
Please add me as a collaborator

**Comment by githubteacher** [comment]
:tada: @carol299 is now a repository collaborator. :balloon:

**Comment by senorita0** [comment]
Add me please

**Comment by githubteacher** [comment]
:tada: @senorita0 is now a repository collaborator. :balloon:

**Comment by zhoufde** [comment]
me too please

**Comment by refrazie** [comment]
add a file for fuquay-varina

**Comment by githubteacher** [comment]
:tada: @zhoufde is now a repository collaborator. :balloon:

**Comment by mcodegeeks** [comment]
pls add me

**Comment by vasu245** [comment]
add me as well

**Comment by githubteacher** [comment]
:tada: @mcodegeeks and @vasu245 are now  repository collaborators. :balloon:

**Comment by natug** [comment]
please add me

**Comment by ehughesDell** [comment]
add me please

**Comment by karlowen** [comment]
Please add me

**Comment by dongrm** [comment]
Add me please.

**Comment by githubteacher** [comment]
:tada: @natug, @ehughesDell, @karlowen, and @dongrm are now  repository collaborators. :balloon:

**Comment by JuhiAsthana** [comment]
Please add me.

**Comment by githubteacher** [comment]
:tada: @JuhiAsthana is now a repository collaborator. :balloon:

**Comment by innjen** [comment]
Add me please

**Comment by geethasreepathi** [comment]
add me

**Comment by monsrud** [comment]
afas

**Comment by pswalker40** [comment]
Please add me as a collaborator

**Comment by monsrud** [comment]
nlkjlk

**Comment by githubteacher** [comment]
:tada: @innjen, @geethasreepathi, @monsrud, @pswalker40, and @monsrud are now  repository collaborators. :balloon:

**Comment by markoholto** [comment]
add me please

**Comment by choudg2** [comment]
Please add me.

**Comment by kolarzhang** [comment]
please add me.

**Comment by githubteacher** [comment]
:tada: @markoholto, @choudg2, and @kolarzhang are now  repository collaborators. :balloon:

**Comment by guotianyang** [comment]
add me

**Comment by mbendure** [comment]
please add

**Comment by mehrer** [comment]
add me please

**Comment by fangy4** [comment]
add me please.

**Comment by githubteacher** [comment]
:tada: @guotianyang, @mbendure, @mehrer, and @fangy4 are now  repository collaborators. :balloon:

**Comment by gearbox2017** [comment]
add me in please

**Comment by ngtim1** [comment]
Try again, please add me.

**Comment by githubteacher** [comment]
:tada: @gearbox2017 is now a repository collaborator. :balloon:

**Comment by milasr** [comment]
Please add me again.

**Comment by ysigit** [comment]
Please add me "collaborator access" so that I could create my own branch

**Comment by githubteacher** [comment]
:tada: @ysigit is now a repository collaborator. :balloon:

**Comment by luol5** [comment]
add me please.

**Comment by luol5** [comment]
Add me please.

**Comment by luol5** [comment]
Add me please.

**Comment by luol5** [comment]
@githubteacher Please add me as a collaborator.

**Comment by MoziUno** [comment]
Late start ... Add-on !!

**Comment by MihirMehta1991** [comment]
Late start add me

**Comment by ranganathhv** [comment]
Lets start, my first comment
