### ISSUE TITLE
Problems with Git Push

### ISSUE THREAD

**Issue by hectorsector** [githubteacher/march-developers#181]
Let's work through the issues going on with pushes on this issue so we can see some historical commands.

**Comment by mburriss** [comment]
> git status
On branch mburriss-hometown
Your branch is ahead of 'origin/mburriss-hometown' by 1 commit.
  (use "git push" to publish your local commits)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   mburriss-raleigh.md



> git commit -m "Add some categories to the Raleigh fil                   e."
[mburriss-hometown 7f4fbab] Add some categories to the Raleigh file.
 1 file changed, 6 insertions(+), 1 deletion(-)


> git status
On branch mburriss-hometown
Your branch is ahead of 'origin/mburriss-hometown' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

> git push
fatal: '/// ATTENTION ///   Are you sure you want to push to public github.com? To override this warning run: 'g                   it adsk enable-public-push github.com/githubteacher/march-developers.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mburriss** [comment]
> git adsk enable-public-push github.com/githubteacher/                   march-developers.git
git: 'adsk' is not a git command. See 'git --help'.

Did you mean one of these?
        add
        dag

**Comment by ngtim1** [comment]
Push still does not work, here is the history of the commands.
 1099  12:52   git clone https://github.com/githubteacher/march-developers.git
  1100  12:52   ls
  1101  12:52   ls -agl
  1102  12:53   cd march-developers/
  1103  12:53   ls
  1104  12:53   ls -agl
  1105  12:53   git status
  1106  12:55   git branch
  1107  12:58   git branch --all
  1108  12:59   git checkout ngtim1-CaryNC
  1109  13:16   git branch
  1110  13:16   git status
  1111  13:19   echo "Cary, NC" > githubngtim1-cary.md
  1112  13:19   ls
  1113  13:19   git status
  1114  13:24   git add githubngtim1-cary.md
  1115  13:24   git status
  1116  13:28   git commit
  1117  13:29   git status
  1118  13:30   vi githubngtim1-cary.md
  1119  13:31   git status
  1120  13:32   git add githubngtim1-cary.md
  1121  13:32   git status
  1122  13:34   git commit -m "Add categories to the Cary file"
  1123  13:34   git status
  1124  13:47   git push

sles12-ngt1-dev-01 scratch/march-developers% git push
fatal: '/// ATTENTION ///   Are you sure you want to push to public github.com? To override this warning run: 'git adsk enable-public-push github.com/githubteacher/march-developers.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by goudreau** [comment]
Same problem as Mike Burriss. Here's my history:

[sles12-goudrb-dev.goudrb]:1030 % git commit
[goudreau-cary 4ea7bcd] I would like to feed your fingertips to the wolverines.
 1 file changed, 1 insertion(+)
 create mode 100644 goudreau-cary.md
[sles12-goudrb-dev.goudrb]:1031 % vi g*
[sles12-goudrb-dev.goudrb]:1032 % git status
On branch goudreau-cary
Your branch is ahead of 'origin/goudreau-cary' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   goudreau-cary.md

no changes added to commit (use "git add" and/or "git commit -a")
[sles12-goudrb-dev.goudrb]:1033 % git add gou*
[sles12-goudrb-dev.goudrb]:1034 % git status
On branch goudreau-cary
Your branch is ahead of 'origin/goudreau-cary' by 1 commit.
  (use "git push" to publish your local commits)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   goudreau-cary.md

[sles12-goudrb-dev.goudrb]:1035 % git commit -m "That's great bass!"
[goudreau-cary a67f1df] That's great bass!
 1 file changed, 6 insertions(+), 1 deletion(-)
[sles12-goudrb-dev.goudrb]:1036 % git push
fatal: '/// ATTENTION ///   Are you sure you want to push to public github.com? To override this warning run: 'git adsk enable-public-push github.com/githubteacher/march-developers.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[sles12-goudrb-dev.goudrb]:1037 % git adsk enable-public-push
git: 'adsk' is not a git command. See 'git --help'.

Did you mean one of these?
        add
        dag
[sles12-goudrb-dev.goudrb]:1038 % git add enable-public-push
fatal: pathspec 'enable-public-push' did not match any files
[sles12-goudrb-dev.goudrb]:1039 % git push
fatal: '/// ATTENTION ///   Are you sure you want to push to public github.com? To override this warning run: 'git adsk enable-public-push github.com/githubteacher/march-developers.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[sles12-goudrb-dev.goudrb]:1040 %

**Comment by hectorsector** [comment]
Thanks @mburriss it looks like your GitHub Enterprise instance is set up to bypass pushes to GitHub.com using a tool called git adsk. I can help troubleshooting it if you show me the results of `git config --list`, but please remove any personally identifiable information before pasting git.

**Comment by mburriss** [comment]
> git config --list
adsk.github.account=burrim
adsk.github.server=durghedev.cec.lab.emc.com
include.path=/home/c4dev/.enterprise/config.include
core.fscache=true
push.default=simple
lfs.batch=true
lfs.concurrenttransfers=10
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
url./// ATTENTION ///   Are you sure you want to push to public github.com? To override this warning run: 'git adsk enable-public-push github.com.pushinsteadof=https://github.com
url./// ATTENTION ///   Are you sure you want to push to public github.com? To override this warning run: 'git adsk enable-public-push github.com.pushinsteadof=git@github.com
url./// ATTENTION ///   Are you sure you want to push to public bitbucket.org? To override this warning run: 'git adsk enable-public-push bitbucket.org.pushinsteadof=https://bitbucket.org
url./// ATTENTION ///   Are you sure you want to push to public bitbucket.org? To override this warning run: 'git adsk enable-public-push bitbucket.org.pushinsteadof=git@bitbucket.org
url./// ATTENTION ///   Are you sure you want to push to public gitlab.com? To override this warning run: 'git adsk enable-public-push gitlab.com.pushinsteadof=https://gitlab.com
url./// ATTENTION ///   Are you sure you want to push to public gitlab.com? To override this warning run: 'git adsk enable-public-push gitlab.com.pushinsteadof=git@gitlab.com
alias.st=status
alias.br=branch
alias.lol=log --pretty=oneline --abbrev-commit --graph --decorate
alias.emc=!f() {         KIT_PATH=$(dirname $(git config include.path)) &&         COMMAND=$1 &&         if [ -n "$COMMAND" ]; then             shift 1;         fi &&         if [ -z "$COMMAND" ] || [ "$COMMAND" = "setup" ]; then             TMP_SETUP=$(mktemp -t git-enterprise-kit.XXXXXX) &&             cp "$KIT_PATH/setup.sh" "$TMP_SETUP" &&             bash "$TMP_SETUP" "$KIT_PATH" $@ &&             rm "$TMP_SETUP";         elif [ -e "$KIT_PATH/$COMMAND.sh" ]; then             bash "$KIT_PATH/$COMMAND.sh" $@;         else             echo "Enterprise Config command '$COMMAND' not found.";         fi     }; f
credential.helper=cache --timeout=86400
user.name=Michael Burriss
user.email=michael.burriss@dell.com
core.autocrlf=input
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/githubteacher/march-developers.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.mburriss-hometown.remote=origin
branch.mburriss-hometown.merge=refs/heads/mburriss-hometown

**Comment by mburriss** [comment]
It is trying to use my local git account at work?  Does that have to match my github.com public account?

**Comment by hectorsector** [comment]
Thanks! I removed the comment since it contains some confidential info but it's very helpful. Give me a sec to see how we can bypass that.

**Comment by mburriss** [comment]
Oh.  Okay.  :)

**Comment by milasr** [comment]
Here's my problem with push:
git push milasr-hopkinton.md
fatal: Invalid gitfile format: milasr-hopkinton.md
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.






Here's git status:

git status
On branch milasr-hometown
Your branch is ahead of 'origin/milasr-hometown' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

**Comment by hectorsector** [comment]
> git push milasr-hopkinton.md

@milasr you can push a branch, but not a file. Try this: `git push`

**Comment by milasr** [comment]
Thanks.

**Comment by ngtim1** [comment]
I have the same problem with M. Burriss, waiting for the way to bypass the local.

**Comment by hectorsector** [comment]
Working on it! Hang tight @mburriss @ngtim1 @goudreau

**Comment by hectorsector** [comment]
Do you all work at the same place? You don't have to tell me where 😉

**Comment by ngtim1** [comment]
Yes.

**Comment by goudreau** [comment]
Hector, note that all three of us are co-workers and have the same work environment

**Comment by mburriss** [comment]
Yes, we do.  But not "all" of us have failed.  @EricVook  is working.

**Comment by hectorsector** [comment]
Very helpful! @EricVook could you please show me your configs with `git config --list`? You can send it privately on GTW if you'd like so your personal details aren't public.

**Comment by goudreau** [comment]
I said "all three of us", not "all of us"!

**Comment by mburriss** [comment]
:)  I was just letting him know that someone on here was working.

**Comment by goudreau** [comment]
We also want to make sure that any changes we make to our environment to make the classwork function correctly can be undone afterward so that it does not screw up our work GitHub setup.

**Comment by hectorsector** [comment]
@mburriss @ngtim1 @goudreau according to your configs, there's this path in your configuration, could you please ensure the path actually exists? 

```
include.path=/home/c4dev/.enterprise/config.include
```

You can react to this message with a 👍 if it exists or a 👎 if it doesn't, or just drop a note.

**Comment by goudreau** [comment]
No such file or directory

**Comment by mburriss** [comment]
@hectorsector The contents in there seem to have a section that specifically blocks us from the public github.

###############################################################################
# Configure push protection to public Git hosting services
###############################################################################

**Comment by hectorsector** [comment]
That's helpful, thanks @mburriss. I've reached out to @EricVook to see if we can figure out why it works for him and not you. One workaround may be to copy his `config.include` file which may contain the right settings.

**Comment by mburriss** [comment]
Figured it out.  For others here at DELL EMC we cannot be our dev VM's local user.  I had to use my corp login.

**Comment by mburriss** [comment]
When I did that it prompted me for my github login/password and then it worked.

**Comment by hectorsector** [comment]
Glad to hear it @mburriss. Since I think that'll work for anyone else that was having the same issue, I will go ahead and close it out but anyone should feel free to reopen if they're still having issues.

**Comment by mburriss** [comment]
Folks may have to "chmod -R 777 ." to fix the permissions on the march-developers dir, but that is how I got it to work.

**Comment by chrismartino** [comment]
A little late to the party, but the command to allow pushes for EMCers is:

`git emc enable-public-push github.com/githubteacher/ march-developers.git`

It looks like whatever enterprise specific scripts emc is using is forked from a project by autodesk, hence the "adsk".

**Comment by EricVook** [comment]
> A little late to the party, but the command to allow pushes for EMCers ...

@chrismartino - you mean this command is required to allow pushes for EMCers _using the Dev VM for the GitHub class_, right?

Because I am able to use GitHub and a local Git on my Windows system, but it does not have the other _baggage_ associated with a DevVM.

**Comment by chrismartino** [comment]
> @chrismartino - you mean this command is required to allow pushes for EMCers using the Dev VM for the GitHub class, right?

Correct, for those of us that are trying to follow along with our Dev VMs, this is the command to use to enable us to do so.

**Comment by EricVook** [comment]
@hectorsector - you wrote

> That's helpful, thanks @mburriss. I've reached out to @EricVook to see if we can figure out why it works for him and not you.

I think it works for me because I'm using my local Windows system and not my Linux Dev VM.
* Perhaps there are some Dev VM settings which require @chrismartino's command or @mburriss workarounds to fix
* Also, I did get the pop-up dialog asking for account information, but I cancelled that and entered my credentials on the command line.
