### ISSUE TITLE
If you are unable to hear

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/march-developers#2]
We recommend trying the phone option in GoToWebinar!

**Comment by hectorsector** [comment]
Drop a note here if you need any help with sound problems!

**Comment by venedara** [comment]
Thank you

**Comment by gmacario** [comment]
Works fine for me, thanks!

**Comment by gsirsat** [comment]
add me please

**Comment by hectorsector** [comment]
> add me please

@gsirsat we're about to get to that step now, Cynthia is about to give those instructions out

**Comment by hectorsector** [comment]
Since it looks like we've figured out any sound problems and we don't have any issues, I'm going to go ahead and close this issue. Feel free to reopen if you have any questions.
