### ISSUE TITLE
Please add as a collaborator - Thanks!

### ISSUE THREAD

**Issue by casemm01** [githubteacher/march-developers#4]

**Comment by monsrud** [comment]
Me too

**Comment by hug-yq** [comment]
Please add me,thanks

**Comment by kolarzhang** [comment]
add me pls.

**Comment by mcodegeeks** [comment]
add me pls too.

**Comment by SuiHoang** [comment]
Please add me.  Thanks !

**Comment by hectorsector** [comment]
Please leave a note in issue #1 and we can add you as a collaborator there. Once you've done that just let me know and I will close out this issue.

**Comment by monsrud** [comment]
added
