### ISSUE TITLE
Add a file for @leefp - Brookline

### ISSUE THREAD

**Issue by leefp** [githubteacher/march-developers#51]
# Adding file for Brookline, MA (where my people are....)

- [x] Get balls...
- [x] start juggling...
- [x]  ride unicycle
- [x]  combine 2 & 3
- [x] receive applause from audience
- [x] bow

**Comment by mhamel12** [comment]
You are missing a step... "fall on my a....."

**Comment by mhamel12** [comment]
Other than that... LGTM
