### ISSUE TITLE
Add a file for ericvook hometown Albuquerque

### ISSUE THREAD

**Issue by EricVook** [githubteacher/march-developers#70]
# Create a file for hometown recommendations

- [x] Create a branch
- [x]  Add a file and commit my changes
- [x]  Open a pull requests
- [x]  Get a code review
- [x]  Get approval
- [x]  Merge the pull request

**Comment by warrenburnside** [comment]
#70 is still broken:(

**Comment by EricVook** [comment]
@warrenburnside - what is broken? Is it looking better now?

**Comment by EricVook** [comment]
Closing.
